name: main
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Need all tags to get a version number in-between tags
            - uses: actions/setup-node@v4
              with:
                  cache: 'yarn'
            - run: yarn --frozen-lockfile
            - run: yarn build

    prettier:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  cache: 'yarn'
            - run: yarn --frozen-lockfile
            - run: ./node_modules/.bin/prettier --check .
